In [2]:
import pandas as pd

In [3]:
PATH = 'Dataset/'

In [4]:
customers = pd.read_csv(PATH+'customers.csv')
merchants = pd.read_csv(PATH + 'merchants.csv')
fail_transaction = pd.read_csv(PATH+'transaction_failures.csv')
transactions = pd.read_csv(PATH+'transactions.csv')

## Customer

In [6]:
customers.sample(5)

,customer_id,customer_name,age,gender,city,state,signup_date,customer_segment,preferred_payment_method
8313,CUST008314,Customer_008314,50,Female,Hyderabad,Telangana,2024-05-04,Regular,Credit Card
15714,CUST015715,Customer_015715,42,Male,Jaipur,Rajasthan,2024-04-14,Regular,UPI
5299,CUST005300,Customer_005300,63,Female,Mumbai,Maharashtra,2025-01-13,New,Debit Card
14707,CUST014708,Customer_014708,44,Male,Hyderabad,Telangana,2023-06-13,Regular,UPI
1257,CUST001258,Customer_001258,35,Male,Coimbatore,Tamil Nadu,2024-12-06,Regular,Credit Card

In [13]:
customers.shape

(20000, 9)

In [7]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               20000 non-null  str
 1   customer_name             20000 non-null  str
 2   age                       20000 non-null  int64
 3   gender                    20000 non-null  str
 4   city                      20000 non-null  str
 5   state                     20000 non-null  str
 6   signup_date               20000 non-null  str
 7   customer_segment          20000 non-null  str
 8   preferred_payment_method  20000 non-null  str
dtypes: int64(1), str(8)
memory usage: 1.4 MB

In [8]:
customers.isnull().sum()

customer_id                 0
customer_name               0
age                         0
gender                      0
city                        0
state                       0
signup_date                 0
customer_segment            0
preferred_payment_method    0
dtype: int64

In [11]:
## Duplicate ID
customers['customer_id'].nunique()

20000

In [15]:
## Check segment
customers['customer_segment'].value_counts()

customer_segment
Regular    13037
New         3941
Premium     3022
Name: count, dtype: int64

In [16]:
customers['preferred_payment_method'].value_counts()

preferred_payment_method
UPI            10954
Debit Card      3023
Credit Card     2947
Net Banking     1543
Wallet          1533
Name: count, dtype: int64

---
## Merchants Dataset

In [18]:
merchants.sample(5)

,merchant_id,merchant_name,category,city,state,merchant_type,onboarding_date
128,MER00129,Merchant_00129,Education,Delhi,Delhi,Hybrid,2022-09-17
228,MER00229,Merchant_00229,Travel,Kolkata,West Bengal,Online,2022-02-17
1831,MER01832,Merchant_01832,Grocery,Delhi,Delhi,Hybrid,2021-09-01
1391,MER01392,Merchant_01392,Entertainment,Lucknow,Uttar Pradesh,Offline,2021-08-18
141,MER00142,Merchant_00142,Food,Hyderabad,Telangana,Offline,2024-07-01

In [19]:
merchants.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   merchant_id      2000 non-null   str
 1   merchant_name    2000 non-null   str
 2   category         2000 non-null   str
 3   city             2000 non-null   str
 4   state            2000 non-null   str
 5   merchant_type    2000 non-null   str
 6   onboarding_date  2000 non-null   str
dtypes: str(7)
memory usage: 109.5 KB

In [20]:
merchants.shape

(2000, 7)

In [21]:
merchants['merchant_id'].nunique()

2000

In [22]:
merchants['merchant_type'].unique()

<StringArray>
['Offline', 'Hybrid', 'Online']
Length: 3, dtype: str

In [24]:
merchants['category'].value_counts()

category
Grocery          445
Food             325
Fashion          211
Utilities        181
Other            172
Healthcare       155
Electronics      145
Entertainment    141
Travel           127
Education         98
Name: count, dtype: int64

In [23]:
merchants.isnull().sum()

merchant_id        0
merchant_name      0
category           0
city               0
state              0
merchant_type      0
onboarding_date    0
dtype: int64

---
## Transactions Dataset

In [25]:
transactions.sample(5)

,transaction_id,customer_id,merchant_id,transaction_datetime,amount,payment_method,transaction_status,city,state,device_type,transaction_type
5684,TXN00005685,CUST010953,MER00701,2025-02-27 13:00:00,323.44,Debit Card,Success,Chennai,Tamil Nadu,Android,Purchase
255128,TXN00255129,CUST017768,MER00648,2025-07-09 09:00:00,284.36,UPI,Success,Jaipur,Rajasthan,Android,Purchase
88959,TXN00088960,CUST005213,MER00781,2025-10-01 23:00:00,676.06,Debit Card,Success,Ranchi,Jharkhand,Android,Purchase
7673,TXN00007674,CUST010354,MER00907,2025-05-28 22:00:00,519.93,Credit Card,Success,Patna,Bihar,iOS,Purchase
12455,TXN00012456,CUST003402,MER01193,2025-11-15 15:00:00,267.65,Credit Card,Success,Coimbatore,Tamil Nadu,Android,Purchase

In [26]:
transactions.shape

(300000, 11)

In [27]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 11 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        300000 non-null  str
 1   customer_id           300000 non-null  str
 2   merchant_id           300000 non-null  str
 3   transaction_datetime  300000 non-null  str
 4   amount                300000 non-null  float64
 5   payment_method        300000 non-null  str
 6   transaction_status    300000 non-null  str
 7   city                  300000 non-null  str
 8   state                 300000 non-null  str
 9   device_type           300000 non-null  str
 10  transaction_type      300000 non-null  str
dtypes: float64(1), str(10)
memory usage: 25.2 MB

In [28]:
transactions.isnull().sum()

transaction_id          0
customer_id             0
merchant_id             0
transaction_datetime    0
amount                  0
payment_method          0
transaction_status      0
city                    0
state                   0
device_type             0
transaction_type        0
dtype: int64

In [29]:
transactions['transaction_id'].nunique()

300000

In [30]:
transactions['amount'].describe()

count    300000.000000
mean       1645.254122
std        3497.066185
min          20.000000
25%         360.810000
50%         683.270000
75%        1506.910000
max      100000.000000
Name: amount, dtype: float64

---
## Fail Transaction Dataset

In [32]:
fail_transaction.sample(5)

,failure_id,transaction_id,failure_reason,retry_attempt,resolution_status
4961,FAIL0004962,TXN00105358,Insufficient Balance,2,Resolved
1343,FAIL0001344,TXN00029848,Bank Server Error,1,Unresolved
10032,FAIL0010033,TXN00215928,Limit Exceeded,1,Unresolved
13055,FAIL0013056,TXN00279865,Payment Gateway Error,2,Resolved
8962,FAIL0008963,TXN00192653,Limit Exceeded,3,Resolved

In [33]:
fail_transaction.isnull().sum()

failure_id           0
transaction_id       0
failure_reason       0
retry_attempt        0
resolution_status    0
dtype: int64

In [35]:
fail_transaction.shape

(13957, 5)

In [36]:
fail_transaction['failure_id'].nunique()

13957

In [37]:
fail_transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 13957 entries, 0 to 13956
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   failure_id         13957 non-null  str
 1   transaction_id     13957 non-null  str
 2   failure_reason     13957 non-null  str
 3   retry_attempt      13957 non-null  int64
 4   resolution_status  13957 non-null  str
dtypes: int64(1), str(4)
memory usage: 545.3 KB

In [39]:
fail_transaction['failure_reason'].value_counts()

failure_reason
Bank Server Error        3089
Insufficient Balance     2694
Payment Gateway Error    2314
Limit Exceeded           2045
Network Error            1911
Invalid PIN               969
Timeout                   935
Name: count, dtype: int64

In [42]:
fail_transaction.resolution_status.value_counts()

resolution_status
Resolved      8603
Unresolved    5354
Name: count, dtype: int64

---
## Check relationships

In [51]:
check = transactions[['transaction_id', 'customer_id']].merge(customers[['customer_id','customer_name']], on = 'customer_id', how = 'left')

In [55]:
check.head()

  transaction_id customer_id    customer_name
0    TXN00000001  CUST004743  Customer_004743
1    TXN00000002  CUST006791  Customer_006791
2    TXN00000003  CUST005666  Customer_005666
3    TXN00000004  CUST017424  Customer_017424
4    TXN00000005  CUST016289  Customer_016289

In [54]:
# transactions.customer_id
check.isnull().sum()

transaction_id    0
customer_id       0
customer_name     0
dtype: int64

In [58]:
check = transactions[['transaction_id', 'merchant_id']].merge(merchants[['merchant_id', 'merchant_name']], on = 'merchant_id', how = 'left')

In [59]:
check.isnull().sum()

transaction_id    0
merchant_id       0
merchant_name     0
dtype: int64

In [60]:
check.head()

  transaction_id merchant_id   merchant_name
0    TXN00000001    MER00433  Merchant_00433
1    TXN00000002    MER00727  Merchant_00727
2    TXN00000003    MER00182  Merchant_00182
3    TXN00000004    MER00579  Merchant_00579
4    TXN00000005    MER00358  Merchant_00358